insert into public.download_files (
  slug,
  title,
  file_type,
  version,
  storage_path,
  filename,
  content_type,
  active,
  published_at,
  notes
)
values
  (
    'rye-creek-gpx',
    '01 Rye Creek GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/01-rye-creek.gpx',
    '01-rye-creek.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 01 - Rye Creek.'
  ),
  (
    'tonto-basin-gpx',
    '02 Tonto Basin GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/02-tonto-basin.gpx',
    '02-tonto-basin.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 02 - Tonto Basin.'
  ),
  (
    'juniper-canyon-gpx',
    '03 Juniper Canyon GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/03-juniper-canyon.gpx',
    '03-juniper-canyon.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 03 - Juniper Canyon.'
  ),
  (
    'cherry-creek-gpx',
    '04 Cherry Creek GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/04-cherry-creek.gpx',
    '04-cherry-creek.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 04 - Cherry Creek.'
  ),
  (
    'canyon-point-gpx',
    '05 Canyon Point GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/05-canyon-point.gpx',
    '05-canyon-point.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 05 - Canyon Point.'
  ),
  (
    'legacy-ranch-gpx',
    '06 Legacy Ranch GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/06-legacy-ranch.gpx',
    '06-legacy-ranch.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 06 - Legacy Ranch.'
  ),
  (
    'deer-springs-lookout-gpx',
    '07 Deer Springs Lookout GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/07-deer-springs-lookout.gpx',
    '07-deer-springs-lookout.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 07 - Deer Springs Lookout.'
  ),
  (
    'border-line-gpx',
    '08 Border Line GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/08-border-line.gpx',
    '08-border-line.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 08 - Border Line.'
  ),
  (
    'porter-mountain-gpx',
    '09 Porter Mountain GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/09-porter-mountain.gpx',
    '09-porter-mountain.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 09 - Porter Mountain.'
  ),
  (
    'greens-peak-gpx',
    '10 Greens Peak GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/10-greens-peak.gpx',
    '10-greens-peak.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 10 - Greens Peak.'
  ),
  (
    'little-colorado-river-gpx',
    '11 Little Colorado River GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/11-little-colorado-river.gpx',
    '11-little-colorado-river.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 11 - Little Colorado River.'
  ),
  (
    'black-river-gpx',
    '12 Black River GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/12-black-river.gpx',
    '12-black-river.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 12 - Black River.'
  ),
  (
    'hannagan-gpx',
    '13 Hannagan GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/13-hannagan.gpx',
    '13-hannagan.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 13 - Hannagan.'
  ),
  (
    'balke-cabin-gpx',
    '14 Balke Cabin GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/14-balke-cabin.gpx',
    '14-balke-cabin.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 14 - Balke Cabin.'
  ),
  (
    'johns-canyon-gpx',
    '15 Johns Canyon GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/15-johns-canyon.gpx',
    '15-johns-canyon.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 15 - Johns Canyon.'
  ),
  (
    'mamie-creek-gpx',
    '16 Mamie Creek GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/16-mamie-creek.gpx',
    '16-mamie-creek.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 16 - Mamie Creek.'
  ),
  (
    'milligan-valley-gpx',
    '17 Milligan Valley GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/17-milligan-valley.gpx',
    '17-milligan-valley.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 17 - Milligan Valley.'
  ),
  (
    'south-fork-gpx',
    '18 South Fork GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/18-south-fork.gpx',
    '18-south-fork.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 18 - South Fork.'
  ),
  (
    'carnero-lake-gpx',
    '20 Carnero Lake GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/20-carnero-lake.gpx',
    '20-carnero-lake.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 20 - Carnero Lake.'
  ),
  (
    'land-of-the-pioneers-gpx',
    '21 Land of the Pioneers GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/21-land-of-the-pioneers.gpx',
    '21-land-of-the-pioneers.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 21 - Land of the Pioneers.'
  ),
  (
    'lone-pine-dam-gpx',
    '23 Lone Pine Dam GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/23-lone-pine-dam.gpx',
    '23-lone-pine-dam.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 23 - Lone Pine Dam.'
  ),
  (
    'maverick-west-gpx',
    '24 Maverick West GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/24-maverick-west.gpx',
    '24-maverick-west.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 24 - Maverick West.'
  ),
  (
    'many-draws-gpx',
    '25 Many Draws GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/25-many-draws.gpx',
    '25-many-draws.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 25 - Many Draws.'
  ),
  (
    'chevelon-crossing-gpx',
    '26 Chevelon Crossing GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/26-chevelon-crossing.gpx',
    '26-chevelon-crossing.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 26 - Chevelon Crossing.'
  ),
  (
    'canyon-lands-gpx',
    '27 Canyon Lands GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/27-canyon-lands.gpx',
    '27-canyon-lands.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 27 - Canyon Lands.'
  ),
  (
    'view-after-view-gpx',
    '28 View After View GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/28-view-after-view.gpx',
    '28-view-after-view.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 28 - View After View.'
  ),
  (
    'the-rim-gpx',
    '29 The Rim GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/29-the-rim.gpx',
    '29-the-rim.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 29 - The Rim.'
  ),
  (
    'doll-baby-gpx',
    '30 Doll Baby GPX',
    'GPX',
    'V5 / Mar 21, 2026',
    'segments/30-doll-baby.gpx',
    '30-doll-baby.gpx',
    'application/gpx+xml',
    true,
    '2026-03-21',
    'Individual GPX for Arizona Alpine Trail Segment 30 - Doll Baby.'
  )
on conflict (slug) do update set
  title = excluded.title,
  file_type = excluded.file_type,
  version = excluded.version,
  storage_path = excluded.storage_path,
  filename = excluded.filename,
  content_type = excluded.content_type,
  active = excluded.active,
  published_at = excluded.published_at,
  notes = excluded.notes,
  updated_at = now();
